export type UserRole = 
  | 'SUPER_ADMIN'       // MODO DIOS: Developers / Dueños de WhatsCloud
  | 'PLATFORM_SUPPORT'  // EMPLEADO WHATSCLOUD: Soporte Técnico
  | 'ACCOUNT_OWNER'     // CLIENTE: Dueño del Negocio (Paga suscripción)
  | 'ACCOUNT_AGENT';    // CLIENTE: Vendedor/Empleado del negocio

// GRABOVOI NUMEROLOGY PROTOCOLS
export type SystemProtocol = 
  | 'SUCCESS_519_7148'   // Validación, Cierre, Éxito
  | 'ABUNDANCE_318_798'  // Prospecting, ROI, Leads
  | 'PROTECTION_8888'    // Seguridad, Admin, Errores
  | 'ETERNAL_MEMORY_719_31'; // Retención de datos, aprendizaje

export interface Lead {
  id: string;
  businessName: string;
  phone: string;
  email: string | null;
  address: string;
  category: string;
  // Google Maps Specifics
  rating?: number;
  reviews?: number;
  mapsUrl?: string;
  status: 'new' | 'exported_wc' | 'exported_crm';
  // Social Media Recon (New)
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    website?: string;
  };
  // Intelligence Singularity
  analysis?: string; // AI Strategy generated by Gemini
}

export interface ACCProfile {
  userId: string;
  name: string;
  role: UserRole; // RBAC Field
  subscriptionStatus: 'active' | 'inactive' | 'expired';
  credits: number;
  defaultLocation: {
    country: string;
    state: string;
    city: string;
    colonia: string;
  };
  pbxExtension?: string; // Linked SIP Extension
}

export interface SearchFilters {
  niche: string;
  country: string;
  state: string;
  city: string;
  colonia: string;
}

// Strict ACC Integration Structure
export interface ACCLeadPayload {
  lead_info: {
    name: string;
    rating: number;
    reviews: number;
    address: string;
    phone: string;
    maps_url: string;
    email?: string | null;
    social_links?: any;
  };
  acc_meta: {
    source: string;
    Ubicacion: string;
    status: string;
  };
}

export interface N8NPayload {
  action: 'update_leads' | 'deduct_credits' | 'sms_campaign' | 'voice_campaign' | 'initiate_call' | 'bot_flow' | 'create_channel' | 'link_extension' | 'admin_adjust_credits' | 'acc_sync_config';
  userId: string;
  timestamp: string;
  module: 'LeadScrapper' | 'BotBuilder' | 'SMSReminder' | 'VoiceCampaigns' | 'Connections' | 'AdminPanel';
  role: UserRole;
  // Aurum Capital Holding Meta-Data
  holding_identity: {
    entity: 'Aurum Capital Holding';
    engine: 'WhatsCloud Ecosistema';
    active_protocol: SystemProtocol;
  };
  data: any;
}

// --- BOT BUILDER TYPES ---

export type SmartActionType = 'image' | 'button' | 'list' | 'input' | 'wait' | 'handover';

export interface SmartAction {
  id: string;
  triggerCode: string; // e.g., {{ACTION_MENU_MAIN}}
  type: SmartActionType;
  name: string; // Internal name
  content: {
    text?: string; // Caption or Body text
    url?: string; // For images
    buttons?: string[]; // For Quick Reply (Max 3)
    listTitle?: string; // For List Header
    listRows?: string[]; // For List Options (Max 10)
    inputPlaceholder?: string; // For 'input' type
    waitSeconds?: number; // For 'wait' type
  };
}

export interface BotConfig {
  systemPrompt: string;
  knowledgeBase: string; // New: Context injection field
  temperature: number;
  actions: SmartAction[];
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  actionTriggered?: SmartAction; // If the bot sent a smart action
  timestamp: Date;
}

// --- MEMORY SYSTEM TYPES (NEW) ---
export interface LongTermMemory {
  user_name?: string;
  user_preferences?: string[]; // e.g., ["likes pepperoni", "hates onions"]
  last_topic?: string;
  sentiment?: 'positive' | 'neutral' | 'negative';
  contact_info?: {
    phone?: string;
    email?: string;
  };
  custom_facts?: Record<string, string>;
}

// --- SMS CAMPAIGN TYPES ---

export interface SMSAudienceMember {
  id: string;
  phone: string;
  name: string;
  source: 'lead_scrapper' | 'csv_import' | 'manual';
}

export interface SMSCampaignConfig {
  campaignName: string;
  message: string;
  audience: SMSAudienceMember[];
  scheduledDate?: Date;
}

// --- VOICE CAMPAIGN TYPES (NEW) ---

export interface VoiceCampaignConfig {
  campaignName: string;
  type: 'tts' | 'audio_file';
  ttsText?: string;
  audioFileName?: string;
  audience: SMSAudienceMember[]; // Reusing Audience Type
  scheduledDate?: string; // ISO String for datetime
}

export interface VoiceCampaignHistoryItem {
    id: string;
    name: string;
    date: string;
    status: 'completed' | 'scheduled' | 'failed';
    answered: number;
    failed: number;
    cost: number;
}

export interface PbxExtension {
  extension: string;
  secret: string; // Never shown in UI, handled by N8N
  status: 'online' | 'offline' | 'unregistered';
  agentName: string;
}

// --- CONNECTIONS / CHATWOOT TYPES ---

export interface ChatwootChannel {
  id: string;
  name: string;
  type: 'whatsapp_api' | 'web_widget';
  identifier: string; // Phone number or Website URL
  status: 'active' | 'disconnected' | 'pending';
  inboxToken?: string;
  webhookStatus: 'healthy' | 'error';
}